### ISSUE TITLE
[textConnect] Localization needed

### ISSUE THREAD

**Issue by theredspoon** [kintone/plugin-examples#128]
Here are files I noticed need an English-language translation:

- settings.html, all over [plugin settings page]
- confirm() text in desktop.js on line 168 [message box]
- checkValues() in config.js on line 119 [error handling]

I don't think I missed anything but another pair of eyes is always welcome.

**Comment by theredspoon** [comment]
@will-yama I believe pull request #136 completed the fix for this issue and we can now close.

**Comment by will-yama** [comment]
Yes thanks this is closed with #136
