### ISSUE TITLE
[textConnect] Multiple-character delimiters need decoding

### ISSUE THREAD

**Issue by theredspoon** [kintone/plugin-examples#144]
When using a delimiter with multiple characters such as ", " or "  ", the space character is converted to "&nbsp;"

There may be other characters that are not properly HTML decoded but I have not tested.

**Comment by will-yama** [comment]
Just checking this... you mean that the spaces turn into the string "\&nbsp;\", correct?

**Comment by theredspoon** [comment]
Yes, exactly

**Comment by will-yama** [comment]
Fixed with #147
